### ISSUE TITLE
matomo

### ISSUE THREAD

**Issue by bnomei** [schnti/kirby-piwik#2]
any changes necessary for this plugin since [piwik is now matomo](https://matomo.org/blog/2018/01/piwik-is-now-matomo/)?

**Comment by mciszczon** [comment]
I did not go in-depth with it, but the answer is: no, _probably_.

If you look into Matomo source files, they are still called `piwik`, e.g. `piwik.js` etc. Moreover, if you download Matomo from the official site, the file is still called `piwik.zip`.

My guess is that they did change the name, but wanted to keep it as much backward compatible as possible. All in all, there's no real reason to change filenames when the files stay the same in the content.

Yeah, it might be confusing and Matomo may change those files' names in the future. But for now it should work.

I'm gonna try this plugin out in the near future and will come back here with the information.

**Comment by mciszczon** [comment]
I confirm it is working just as expected, no changes are neccessary. At least when it comes to self-hosted ~Piwik~ Matomo. I have never used their cloud-hosted version.
